### ISSUE TITLE
Slow ALS computation and inaccurate time measurements

### ISSUE THREAD

**Issue by jacekwasilewski** [RankSys/RankSys#2]
Hi @saulvargas,

I wanted to run HKV ALS method to generate recommendations for some relatively huge, sparse matrix - 4M of users, 500k of items. I was expecting that to take long time however I how feeling it takes bit longer that it should or/and reports execution time that is not accurate.

After around 3 hours of run, first iteration has finished and it reported that it took only 832s. I looked in the code and I see that  `error(...)` is called outside the block of which we measure the execution time. My intuition is that calculation of the square loss should take less than one iteration of the factorisation but then the numbers still would not sum up to be somewhere close to these 3 hours.

1) Is there a point in calling `error(...)` separately to get the square loss? Maybe this calculation could be done together with minimising the P and Q? Or maybe we could parametrise that to keep it only if we need to get it and that could make it a bit faster?
2) Maybe adding more logging to crucial parts of the framework could help us in understanding what is happening when we run some algorithms and how long each part takes?

Jacek.

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

1) The calculation of the square loss is only for testing purposes. In code that needs to run as fast as possible, you may turn off the logging at INFO level and thus the error won't be calculated. I'll take a look at the timing issue: the factorisation step should definitely take more that the calculation of the error. **EDIT: when the number of items is really large and the user-items pairs sparse, the calculation of the prediction error can be actually much higher than the factorisation steps!**

2) In order to know about the running time of the algorithms, I'd say here that profiling is your friend.

I'll get back to you if I discover anything odd with the timing thing.

Saúl

**Comment by saulvargas** [comment]
Hi again:

I've been thinking about the issue timing and, although I haven't tested it with a dataset as yours, I think I know what's happening... and it is the case that it takes more to compute the error (which is only informative and useless otherwise) than the factorisation itself.

It is actually quite simple. For each user, the product of the user vector with THE WHOLE item matrix is calculated. That, in your case, is a big calculation!

PROPOSED SOLUTION: set the logging message that triggers the computation of the error to an even less prioritary level. Any other suggestions?

**Comment by jacekwasilewski** [comment]
You're right - using different logging level should do the work.

I've just got some output to share:

```
Jun 08, 2015 6:29:16 PM es.uam.eps.ir.ranksys.mf.als.ALSFactorizer factorize
INFO: iteration   1      831.93s      726199183.646859
Jun 08, 2015 10:34:32 PM es.uam.eps.ir.ranksys.mf.als.ALSFactorizer factorize
INFO: iteration   2      554.91s      499980947.131565
```

I've just check the code and it looks like in the loss computation we iterate over users first and then items for the user, so we're good here. Then we have:

```
double err2 = confidence.applyAsDouble(0) * su.assign(x -> x * x).zSum();
```

so you're right, this might take some time.

## 

Also I've been wondering if we benefit a lot from using parallel streams for such numbers of users and items - I've seen opinions that, especially if the computation of the block we want to parallelise takes longer time, we might get overload and not that good performance. But I haven't checked if we suffer from that in this case.

**Comment by saulvargas** [comment]
In the future the logging code of the ALSFactorizer will look something like this:

```
LOG.log(Level.INFO, String.format("iteration n = %3d t = %.2fs", iter, time1 / 1_000_000_000.0));
LOG.log(Level.FINE, () -> String.format("iteration n = %3d e = %.6f", iter, error(factorization, data)));
```

Well, regarding the parallelisation, I would say it is in general terms quite beneficial. I've just finished a quick test with the MovieLens1M dataset (I know, quite small, but still illustrative) in which I used the HKVFactorizer with 1 to 6 thread threads (by setting java.util.concurrent.ForkJoinPool.common.parallelism). This is what I get (I report only the execution time of the last iteration):

```
n = 1 t = 7.42s
n = 2 t = 6.01s
n = 3 t = 4.82s
n = 4 t = 4.42s
n = 5 t = 3.76s
n = 6 t = 3.77s
```

![img](https://cloud.githubusercontent.com/assets/2616433/8047554/ced977ac-0e3e-11e5-80aa-d4da82879f9e.png)
The first observation is that parallelisation in this dataset (and others that I have worked with such as Netflix) decreases execution time. The second observation is that this decrease does not seem to be linear with the number of threads, which might be possibly related to the thread handling overload that you mention. I am therefore inclined to think that parallelisation is beneficial, just not linear to the number of threads in use.

An interesting read somewhat related to this topic (I did read this one): http://jaxenter.com/fork-join-framework-vs-parallel-streams-vs-executorservice-115769.html?utm_content=bufferd8d4f&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

If you have time to check this or similar observations regarding parallelisation in your dataset, please share!

Regards
P.S. Have you tried using also the PZTFactorizer? It uses some ingenious tricks that make the execution faster (although slightly less accurate)!

**Comment by saulvargas** [comment]
An update of the previoius results, including a quick test with Netflix:
![ml1m](https://cloud.githubusercontent.com/assets/2616433/8048672/958e1d82-0e4c-11e5-9ea4-f97e143c33d5.png)
![netflix](https://cloud.githubusercontent.com/assets/2616433/8048674/97d6506e-0e4c-11e5-89ca-a31c9d0828b0.png)

**Comment by jacekwasilewski** [comment]
I'll try later to get some results for dataset I'm using - although it might take some time, right now I'm using 40 cores and it still takes 15 or so minutes for an iteration.

I think we can close it.
