### ISSUE TITLE
Exception in binomial model when alpha = 1

### ISSUE THREAD

**Issue by nachoft** [RankSys/RankSys#25]
Hi @saulvargas 

It looks like method patience() in class BinomialModel.UserBinomialModel throws an OutOfRangeException (out of [0, 1] range) when alpha = 1. I think the problem is that feature probabilities are not normalized in this particular case in method getUserFeatureProbs()?

Thanks!

**Comment by saulvargas** [comment]
Hi @nachoft 

Thanks a lot for this! I've fixed the code and added a unit test for BinomialModel.

Saúl

**Comment by saulvargas** [comment]
Well... before merging, would you mind taking a look at the commit https://github.com/RankSys/RankSys/commit/192f9590e79cef5ffadd82306a098ddb71b63e9c

**Comment by PinkAppleFlower** [comment]
@saulvargas I think you want to check the line of code for calculating p0

**Comment by PinkAppleFlower** [comment]
In particular, p0 might need to be calculated as (1-pf) raised to the (n-k) power, not to the nth power.  

so:   double p0 = Math.pow(1 - pf, N);

changes to:
  double p0 = Math.pow(1 - pf, (N-k));

**Comment by saulvargas** [comment]
Hi @PinkAppleFlower 

You mean inside the "patience" function? What would be the logic behind that change? Do you think it is related to this bug or it would be another one?

Cheers

**Comment by PinkAppleFlower** [comment]
Hi @saulvargas:
I am not sure, it might be the same issue.  Can you please explain what pf is?

Cheers,

**Comment by saulvargas** [comment]
@PinkAppleFlower, I believe your comment is not strictly related to the current bug.

Please check the paper where the binomial diversity model is presented (http://ir.ii.uam.es/saul/pubs/recsys2014-vargas-tid.pdf) for more details.

**Comment by PinkAppleFlower** [comment]
@saulvargas Okay, you might be right, below are the rest of my comments for this bug currently.  I think my comments are related, because when I look at the patience method, it seems possible for results that are out of bounds to be returned, see below for more details.

The logic behind this change is: 

(1) the Math.power function raises the first argument to the power of the second argument.   

(2) As it is written now, p0 is (1-pf)^N, where N is the total number of items on the list, pf is the number probability that feature f appears in the list, and k is the number of items in the list that have the feature. 

(3) What happens inside the patience function when k is equal to zero (such as when the feature does not appear in any of the items in the list)?  

(4) Does the domain of the cumulative distribution for the binomial random variable include -1? 

(5) Is it possible for k to equal zero, perhaps when alpha is equal to one?  Is there a relationship between alpha and k?

Cheers,
Maureen

**Comment by saulvargas** [comment]
Hi @PinkAppleFlower 

It is not a related issue to the current bug but, anyway, it deserves some comment. Thanks for pointing it out.

Basically, as you can read in the paper, "patience" or "redundancy" penalisation is only applied for the cases where k >= 1. Indeed, we assume that the perfect situation is when you recommend a genre just once in a recommendation, and then k > 1 you start becoming redundant. If you do not recommend the genre but the user likes it, then you do not have a problem of redundancy at all (cannot be defined in that situtation), but a coverage one.

If you think this deserves further discussion, please file a new issue and I will gladly join it.

Saúl
