### ISSUE TITLE
Problem in understanding the score value of the output of fm-rmse

### ISSUE THREAD

**Issue by anis016** [RankSys/RankSys#53]
Hello !

I am bit confused about the "fm-rmse" generated. So, after running I got the output as below

143	300	1.0382524187063291
143	245	0.9832457247884757
143	328	0.9742608167403299
143	302	0.9294914297314028
143	340	0.8702918462742051
143	332	0.8436575245074303
.
.

I understand that, the first column represents the user, the second represents the movie the system recommends to the user. The third is the score the recommendation algorithm generates for that user and movie pair. Now, 
1. What this actually "score" means ? It seems to me that, these are not predicted rating because I couldn't find any score of 2, 3, 4 or 5 .... 
2. Now, with that in mind, is there anyway it is possible to predict the movie rating using this library ?

Maybe I am missing something ! Please help..

Thank you !

**Comment by jacekwasilewski** [comment]
Hi @anis016,
this library is rather designed for the ranking recommendation task, rather than the rating prediction. While some of the implementations might work well on the rating prediction (like matrix factorisations) it is not generally true. The scores are generally used to build ranked lists of recommendation. It is worth pointing out that nowadays the ranking task seems to be more relevant then the rating prediction task.
Jacek

**Comment by anis016** [comment]
uh.. Thank you ! I understand :-)
