### ISSUE TITLE
Command-line programs to generate and evaluate recommendations

### ISSUE THREAD

**Issue by saulvargas** [RankSys/RankSys#6]
There has been some interest (see #3) in including command-line programs that generate and evaluate recommendations wrapping RankSys libraries. Currently, some users are modifying the examples in RankSys-examples as a work-around. Although the original purpose of RankSys was to be used as a library rather than a collection of programs, it is clear that providing such utilities would broaden the user base of the framework.

There are no short term plans for developing these command-line programs. However, in the meantime, I am open to suggestions, proposals and collaborations on this matter.

**Comment by jacekwasilewski** [comment]
Hi @saulvargas,

I was thinking how this could be done.

First, natural, solution could be to have it all wrapped in one CLI program. Like it's been done in LensKit (http://lenskit.org/documentation/cli/lenskit.1.html) or MyMediaLite (http://www.mymedialite.net/documentation/rating_prediction.html). Apache Commons CLI (https://commons.apache.org/proper/commons-cli/usage.html) could be used to do it.
Personally I think it might become quite complex, in terms of using it (if you have many parameters) and maintenance - I don't have any experience with Commons CLI but it looks like it only helps in parsing arguments.

I was thinking about different solution - to use Spring Shell (http://docs.spring.io/spring-shell/docs/current/reference/htmlsingle/#simple-application) where shell would be created from which you would run commands to train, evaluate, rerank etc. Each task would have its own component, with needed arguments. Disadvantage of this solutions is (I think) that it would be impossible to chain it, e.g. in a workflow.

Actually, now I think that instead of creating such command-line program as a part of RankSys maybe it would make more sense to create a separate project which could include not only what you're created but maybe other libraries as well. What do you think? I could start working on such thing.

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

Thanks for your vauable insights. Some comments:

1) Indeed, my main fear is that command-line applications tend to become more complex than the underlying libraries they are wrapping the more functionalities of the latter you want to expose with the former. Therefore, the option of CLI  should be kept as simple as possible without pretending to cover everything RankSys is able to do.

2) I understand that Spring Shell would define some kind of internal scripting language for RankSys. I like the idea, although I envision here a lot of work on properly defining such scripting language.

3) Our colleages @alansaid and @abellogin with their rival toolkit https://github.com/recommenders/rival/ are already doing a good job in integrating several recommendation frameworks, although I am not sure whether they have any command-line program or plans to release it.

Cheers

**Comment by jacekwasilewski** [comment]
1) I checked how they did it at LensKit - https://github.com/lenskit/lenskit/tree/master/lenskit-cli/src/main/java/org/lenskit/cli - if you don't have many argument then it's quite simple and looks ok, although bit low-level to me.

2) It wouldn't be a scripting language because you wouldn't have the ability to assign something to local variables etc. It would be rather some kind of console from which you could just call operations you define. However I see possibilities how we could e.g. simplify executing experiments using such shell. But still, I'm not sure if that should be a part of RankSys.

3) It looks like they have created an issue for that - https://github.com/recommenders/rival/issues/57
